title:              John M. Snyder
email:              snyderjo@gmail.com
description:        >- # this means to ignore newlines until "baseurl:"
  Data professional with years of experience, and diverse interests.
author:             John Snyder
baseurl:            ""
url:                "https://snyderjo.github.io"

# Social Profiles
twitter_username:   
github_username:    snyderjo
facebook_username:  
instagram_username:  
linkedin_username: john-snyder-ab18a034

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
